# in debug_mode no agent directories will be created and no models will be saved
debug_mode: false

# Hardware specifc configurations
# number of parallel environments
n_envs: 1
# gpu yes or no
no_gpu: no


### Global configuration that applies to all robots
# navigation task mode, chose from "random" or "staged"
task_mode: "cases"
# number of simulation timesteps
n_timesteps: 40000000
max_num_moves_per_eps: 650

periodic_eval:
  # max number of steps per episode
  max_num_moves_per_eps: 1000 # 1000
  # number of evaluation episodes
  n_eval_episodes: 100 # 100
  # evaluation frequency, evaluation after every n_envs * 20000 timesteps
  eval_freq: 20000 # 20000

### training_curriculum
# threshold metric to be considered during evaluation
# can be either "succ" (success rate) or "rew" (reward)
training_curriculum:
  # file for the robot's learning curriculum
  training_curriculum_file: "default.yaml"
  threshold_type: "succ"
  upper_threshold: 0.85
  lower_threshold: 0.5

### evaluation_curriculum
# threshold metric to be considered during evaluation
# can be either "succ" (success rate) or "rew" (reward)
evaluation_curriculum:
  # file for the robot's learning curriculum
  evaluation_curriculum_file: "default.yaml"
  threshold_type: "succ"
  upper_threshold: 0.85
  lower_threshold: 0.5

### stop training on threshold
# stops training when last stage reached and threshold satisfied
stop_training:
  threshold_type: "succ"
  threshold: 0.95


### logging
# log interval
log_interval: 1
# save evaluation stats during training in log file
eval_log: false
# use tensorboard
tb: false
# use wandb
wandb: false

global_tasks: true

robots:
  jackal:
    # number of robots of this type
    num_robots: 4
    # name of hyperparameter file located in the configs/hyperparameters directory
    hyperparameter_file: "jackal.json" # "default.json"
    # name of architecture defined in the Policy factory
    architecture_name: "AGENT_24"
    # path to latest checkpoint; if provided the training will be resumed from that checkpoint
    resume: null
  # rto:
  #   # number of robots of this type
  #   num_robots: 2
  #   # name of hyperparameter file located in the configs/hyperparameters directory
  #   hyperparameter_file: "rto.json"
  #   # name of architecture defined in the Policy factory
  #   architecture_name: "AGENT_24"
  #   # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  #   resume: null
  